"""D0a-3's named regression-set exceptions (docs/work/orders/D0a-3-apply-public-readiness.md).

Verification ruled, at the D0a-3 meet, that the example catalog is scrubbed (it overrides
the audit's kept rows), with a named exception for the tests and goldens bound to its
values. Each entry below names the file, what changed and why. The new values are
derived, never invented:
  - the repository key is the placeholder ``example-repo``;
  - the revision is ``sha1(b"example-repo")``, a synthetic 40-hex value;
  - every binding key is the product's own derivation,
    ``kp_agent_tooling._impl.service.desk_identity.binding_key``, of the new coordinates;
  - the T8 golden is regenerated by its committed generator, from the T8 base code, at the
    new coordinates, and two runs write identical bytes.
The OLD values are not recorded in this tree: they are the private values the scrub
removed (a private repository key, a private commit, and the hashes derived from them).
They are listed in the D0a-3 meet packet. tests/test_d0a3_ruled_exceptions.py checks that
the tree carries exactly the new values below.

Frozen fixtures that keep a private mention verbatim are named here as well (KEPT).
"""
from __future__ import annotations

import hashlib

EXAMPLE_TENANT = 'workspace-demo'
EXAMPLE_REPO = 'example-repo'
EXAMPLE_REVISION = hashlib.sha1(EXAMPLE_REPO.encode()).hexdigest()

NEW_BINDINGS = {
    'implementation': 'binding:5b7bfb3a38922713141a62006fb7b770e436a30eed056e29b6a41d44fe52c296',
    'verification': 'binding:888862c55bd8e8e902828a81a4991f86cf6955ffc3e91dbfc2587b42c6b89415',
}

T8_GOLDEN = 'tests/fixtures/t8-claim-note-budget/base-capsule.json'
T8_GOLDEN_SHA256 = 'ce9b04f33d8a35ccbf470b48f65c0459291c538562607ccdb35efe81774fb795'
T8_NEW_IDS = {
    'binding': NEW_BINDINGS['implementation'],
    'episode_id': 'episode:sha256:f0f4a650792d157491edcde8d2a44da3126e1dcde24c57d627a4eecd162be222',
    'capsule_id': 'episode-capsule:sha256:bf04acc892c92e9d28c6c8818ed07294a14ab28068dc079784d053dd6eef9b18',
}

T11A_CORPUS = 'tests/fixtures/t11a/identity_corpus.json'
T11A_CORPUS_SHA256_AT_D0A3 = 'b0ce6ebe72c8485c6fc34048359cee2dde341b1330f48a4b5b6d911f47457298'  # informational

EXCEPTIONS = {
    'E1 example catalog': (
        'config/desk-context/catalog.example.json, config/desk-context/memory.example.json and the packaged '
        'copy packages/tooling/src/kp_agent_tooling/assets/desk-context/catalog.example.json: the repository '
        'key, the source revision and the binding keys of both desks (in each catalog, and as the memory fixture keys) take '
        'the derived values above.'),
    'E2 T8 golden': (
        T8_GOLDEN + ': regenerated by tests/fixtures/t8-claim-note-budget/generate_base_capsule.py from an '
        'export of the T8 base code, at the new example coordinates. At the old coordinates the generator '
        'reproduces the old golden byte for byte (checked at D0a-3), except its two descriptive fields, '
        '_comment and base_commit, which no longer carry the private base commit. New ids: T8_NEW_IDS.'),
    'E6 T11a identity corpus': (
        T11A_CORPUS + ': its plan-token site records the example catalog\'s selected desk binding. Regenerated '
        'by its committed generator (tests/fixtures/t11a/generate_identity_corpus.py); the only change is that '
        'binding key, in two bodies, and two runs write identical bytes. identity_corpus_ops.json is '
        'unchanged. The T11b regression-set check stays green: the golden equals its generator\'s output.'),
    'E3 workspace-context pin': (
        'tests/test_workspace_context.py:72-73 asserts the example revision; re-pinned to EXAMPLE_REVISION.'),
    'E4 test data': (
        'tests/test_desk_write_scope.py builds its catalog from a seat abbreviation and two private repository '
        'keys; they become the roster role Deployment Engineering and the keys app and lib. Three prose strings '
        'in extensions/ops/tests/test_commit_rationale.py name the app repository instead of a desk instance. '
        'The assertions are unchanged.'),
    'E5 test prose': (
        'Docstrings, comments and xfail/skip reasons in the tests, the ledger and the T11a/T10/T5 rigs no '
        'longer cite private commits; an order is "frozen at its merge commit", a legacy baseline is "the '
        'extraction commit". No assertion reads them.'),
    'T1 capture: pin removed at D0b, placeholder kept': (
        'tests/boundary/t1_contract.py ORDER_MERGE_BASE was removed at D0b R4a: the frozen pre-move capture now '
        'records pre_move_product_sha256 (the pre-move product\'s content hash, pinned as PRE_MOVE_PRODUCT_SHA256). '
        'The @REV_ATS@/@REPO_ATS@ placeholder key in tests/boundary/t1_harness.py stays bound to that capture; '
        'the capture command needs it unchanged.'),
    'T10 golden: base pins removed at D0b': (
        'The base commit pins were removed at D0b R4a: tests/fixtures/t10-read-path-projection/goldens.json '
        'records meta.generator_sha256 (the generator\'s own hash) and meta.product_sha256 (the base product\'s '
        'content hash, pinned in generate.py as BASE_PRODUCT_SHA256); tests/test_t10_p5_identical_results.py '
        'asserts both. The golden stays frozen at that base.'),
    'KEPT H6 guard value': (
        'tests/docs/test_release_hygiene.py KANBAN_LOCAL_HEAD: H3 asserts that NOTICE never names this private '
        'local branch head; removing the value removes the check.'),
    'KEPT ledger qualifier': (
        'tests/EXTRACTED-TEST-LEDGER.md writes a legacy-repository path directly after the word OPS, and '
        'tests/docs/test_doc_paths.py P3 (and its docstring) keys on that word; the ported tests\' skip and '
        'xfail reasons use the same word. OPS is also the extension\'s public name.'),
    'KEPT pre-move tool surface': (
        'tests/boundary/fixtures/pre_move_tools_list.json is the frozen capture of the pre-move tool surface '
        '(T1). Its four verification.packet descriptions keep a desk instance name verbatim; P3 compares names '
        'and input schemas only, and the capture cannot be regenerated without the pre-move tree.'),
}
