"""Regenerate base-capsule.json, the T8 P4 golden (tests/test_claim_note_budget.py).

The golden is a capsule that the T8 BASE code stored, and what that code read back for
it. It has to be produced by the base code, not by this tree: at the base, a capsule
drew a source qualifier from an uncited event, and P4 checks that the current code
still reads such a stored capsule unchanged.

Usage (from the repository root):

    python tests/fixtures/t8-claim-note-budget/generate_base_capsule.py --base <ref> \\
        [--base-label TEXT] [--catalog-dir config/desk-context] [--out PATH]

<ref> is the Git ref whose tree is the base code: the generator exports its
packages/tooling/src, tests/test_portable_desk_memory.py and config/desk-context with
`git archive` and runs that code in a child interpreter with the export first on its path.
There is no default: the committed golden was produced from T8's frozen base in the private
history, which the public history cannot resolve (see README.md here). --base-label is the
text the golden records for its base. The export's example catalog and doctrine are
replaced by the ones in --catalog-dir (default: this tree's config/desk-context), so the
capsule is bound to the binding key this tree's example derives. Everything else is
synthetic and fixed below. Two runs write identical bytes.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent / 'base-capsule.json'
COMMENT = ('Capsule produced by agent-tooling at the base of order T8 (the commit that froze the order) '
           'through EpisodicMemoryTools memory.propose; the capsule row is stored byte-for-byte and the reads '
           'are what the base code returned for it. Synthetic content. Used by tests/test_claim_note_budget.py '
           '(P4). Regenerated by generate_base_capsule.py in this directory.')
BASE = 'the commit that froze order T8 (private history; not in the public history)'
CAPTURE_SESSION, READ_SESSION = 'session-1', 'session-2'
SOURCE_REF = 't8-legacy:visible-transcript:1'
EVENTS = [
    {'event_id': 'decision', 'role': 'user', 'text': 'Adopt the blue rollout plan. The canary gate was not run.'},
    {'event_id': 'aside', 'role': 'assistant', 'text': 'Staging was never load tested. Keep the old pool warm.'},
]

# Runs inside the child interpreter, against the base code.
CHILD = r'''
import json, sqlite3, sys, tempfile
from contextlib import closing
from pathlib import Path
spec = json.loads(sys.argv[1])
import kp_agent_tooling
assert Path(kp_agent_tooling.__file__).resolve().is_relative_to(Path(spec['base']).resolve()), kp_agent_tooling.__file__
from test_portable_desk_memory import episode_store
from kp_agent_tooling._impl.service.episodic_memory_tools import EpisodicMemoryTools
with tempfile.TemporaryDirectory() as directory:
    store = episode_store(Path(directory))
    tools = EpisodicMemoryTools(store, spec['read_session'])
    episode = store.capture(spec['capture_session'], source_ref=spec['source_ref'], events=spec['events'])['episode_id']
    arguments = {
        'episode_ids': [episode],
        'items': [{'citations': [{'end': 28, 'episode_id': episode, 'event_id': 'decision',
                                  'quote': 'Adopt the blue rollout plan.', 'start': 0}],
                   'kind': 'decision', 'text': 'Adopt the blue rollout plan.'}],
        'unresolved_questions': ['When will the canary gate run?'],
    }
    result = tools.call('memory.propose', arguments)
    capsule = result['capsule_id']
    with closing(sqlite3.connect(store.path)) as db:
        rows = db.execute('SELECT id, binding, payload FROM capsules').fetchall()
    assert len(rows) == 1, rows
    row = {'id': rows[0][0], 'binding': rows[0][1], 'payload': bytes(rows[0][2]).decode('ascii')}
    reads = {
        'memory.handoff': tools.call('memory.handoff', {'capsule_id': capsule}),
        'memory.evidence_directory': tools.call('memory.evidence_directory', {'capsule_id': capsule}),
        'memory.handoff_page': tools.call('memory.handoff_page', {'capsule_id': capsule, 'budget_bytes': 24000}),
        'memory.resume': tools.call('memory.resume', {'capsule_id': capsule, 'budget_bytes': 24000}),
    }
    print(json.dumps({'episode_id': episode, 'propose_arguments': arguments, 'propose_result': result,
                      'capsule_row': row, 'reads': reads}))
'''


EXPORTED = ('packages/tooling/src', 'tests/test_portable_desk_memory.py', 'config/desk-context')


def export(ref: str, work: Path) -> None:
    """Extract the base code of <ref> (the paths above) into work, with git archive."""
    archive = subprocess.run(['git', '-C', str(ROOT), 'archive', '--format=tar', ref, *EXPORTED],
                             capture_output=True)
    if archive.returncode:
        raise SystemExit(archive.stderr.decode())
    work.mkdir(parents=True)
    with tempfile.TemporaryFile() as handle:
        handle.write(archive.stdout)
        handle.seek(0)
        with tarfile.open(fileobj=handle) as tar:
            if hasattr(tarfile, 'data_filter'):
                tar.extractall(work, filter='data')
            else:  # Python < 3.11.4
                tar.extractall(work)


def build(ref: str, catalog_dir: Path, base_label: str = BASE) -> str:
    with tempfile.TemporaryDirectory() as directory:
        work = Path(directory) / 'base'
        export(ref, work)
        for name in ('catalog.example.json', 'doctrine.md'):
            shutil.copyfile(catalog_dir / name, work / 'config' / 'desk-context' / name)
        env = dict(os.environ, PYTHONPATH=os.pathsep.join([str(work / 'packages' / 'tooling' / 'src'),
                                                            str(work / 'tests')]))
        spec = {'base': str(work), 'capture_session': CAPTURE_SESSION, 'read_session': READ_SESSION,
                'source_ref': SOURCE_REF, 'events': EVENTS}
        child = subprocess.run([sys.executable, '-c', CHILD, json.dumps(spec)], env=env, cwd=directory,
                               capture_output=True, text=True)
        if child.returncode:
            raise SystemExit(child.stderr)
        produced = json.loads(child.stdout)
    golden = {'_comment': COMMENT, 'base_commit': base_label, 'capture_session': CAPTURE_SESSION,
              'read_session': READ_SESSION, 'source_ref': SOURCE_REF, 'events': EVENTS, **produced}
    return json.dumps(golden, indent=1, sort_keys=True) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--base', required=True, help='the Git ref whose tree is the base code')
    parser.add_argument('--base-label', default=BASE, help='what the golden records as its base')
    parser.add_argument('--catalog-dir', type=Path, default=ROOT / 'config' / 'desk-context')
    parser.add_argument('--out', type=Path, default=OUT)
    args = parser.parse_args()
    args.out.write_text(build(args.base, args.catalog_dir, args.base_label))


if __name__ == '__main__':
    main()
